### ISSUE TITLE
readme.md: Using with latte

### ISSUE THREAD

**Issue by sallyx** [nette/tokenizer#13]
"Tokenizer is used in Latte for example." -- Is this really true?

**Comment by Majkl578** [comment]
It's not.

**Comment by milo** [comment]
It is true (https://github.com/nette/latte/blob/3b34ec8cefc18eef84072d33717e1118f8d2b45d/src/Latte/Tokenizer.php).

**Comment by hrach** [comment]
It's not. it's a different class, origin may be the same...

**Comment by milo** [comment]
Well, there is the only way how to solve it.

**Comment by sallyx** [comment]
The only way to solve it is 1)Update readme.md here 2) Use this Tokenizer in Nette or 3) Ignore this problem?

**Comment by milo** [comment]
@sallyx  If you want, fix the readme please.

**Comment by dg** [comment]
I think that this is the kind of problem that simply cannot be ignored.
