### ISSUE TITLE
Bad dep. on tester 2.0

### ISSUE THREAD

**Issue by remicollet** [nette/tokenizer#15]
Since: 2ed42cc6c61317c847c2bfb96ae7a865dc88c331

Just released version 2.2.2 requires tester 2.0 which is not released.

**Comment by dg** [comment]
Yes, it installs dev master.

**Comment by remicollet** [comment]
?

**Comment by enumag** [comment]
@remicollet There is `"minimum-stability": "dev"` in composer.json as well which means the installed versions don't have to be stable releases. In this case development version of nette/tester is used.

**Comment by remicollet** [comment]
But using nette/nette 2.3 framework, all component have to be < 2.4, and works with php 5.3

This dep means we need PHP > 5.4, which make impossible to run the tests.
And sorry, but requiring a "dev" version for a stable package seems... uggly.

BTW, test suite pass with tester 1.7

**Comment by enumag** [comment]
Using development version of tester is fine in development stage of tokenizer. I presume that when the next stable version of tokenizer is released nette/tester 2.0 will already be stable as well.

The fact that tests now require PHP 5.6 while the code itself does not is a bit ugly though.

**Comment by dg** [comment]
@remicollet you're right, now is impossible to install devs in PHP 5.3. I'll revert it.

**Comment by remicollet** [comment]
Thanks for 2.2.3
