### ISSUE TITLE
Feature request: "Expect" method for TokenIterator

### ISSUE THREAD

**Issue by mnoskov** [nette/tokenizer#17]
I think this method would be useful.

Like "nextToken", but throwing an exception with position coordinates if it does not match the expected token.

**Comment by JanTvrdik** [comment]
Terminology side note: such method is usually named `consume`.

**Comment by dg** [comment]
IMHO current `next*` works like `consume*`). So more consistent name should be something like `nextTokenOrFail()` & `nextValueOrFail()`. Or `forceNextToken()` & `forceNextValue()`…

**Comment by hrach** [comment]
> more consistent name 

the consitent name is the Jan Tvrdik's proposal.

**Comment by dg** [comment]
Can you explain it?

**Comment by JanTvrdik** [comment]
@dg Your proposal is consistent with your vision for Nette Tokenizer. My proposal is consistent with the rest of the world. But maybe @hrach meant sth else entirely.

**Comment by dg** [comment]
@hrach @majkl578 Is `consume` usual name for a method that throws an exception in the event of failure instead of return null? Can you prove it with some links?

**Comment by JanTvrdik** [comment]
Do those random examples help?

* https://github.com/codeflows/mini-eiffel/blob/589727b79b738afdeac8556dcae87b99107d47df/test/minieiffel/LexerTestCase.java#L18-L28
* https://github.com/Nnamso/fleek/blob/6d43fa948525a2bb97535297cece76183a575769/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php#L6681-L6694
* https://github.com/Xon/dice-roller/blob/2ec1a0ca74ca6eb45e80f19903d5b1a3af67bd85/DiceParser.php#L62-L75
* https://github.com/itsmyfirstday/ProjectCityBuild/blob/4da34b1bfe167bdf40e82e673387d8593f8a21f4/app/Modules/Servers/Services/Minecraft/RateLimitDecorator.php#L45-L61
* https://github.com/u12206050/Andrologists2014/blob/9daa4e993ed8e9e28e1f02d342b0a38724499bee/QuantFacialRecognition/src/ConnectionFileReader.cpp#L87-L100

**Comment by dg** [comment]
I do not know ... 

There are always methods from a higher layer than the tokenizer/lexer itself. So it makes sense to throw an exception when token not found - but it does not seem to me that it is their character.

However, it makes sense from a *linguistic* point of view. It's a verb, *consume!* and if you can't consume, it has sense to throw exception. While nextToken may not be theoretical none, ie null.

**Comment by JanTvrdik** [comment]
> There are always methods from a higher layer than the tokenizer/lexer itself

Well, yes. The job of lexer ends by returning tokens array. The `Stream` object is a helper class used by parser. When no such helper class is available the `consume()` method is usually implemented as part of parser.

Maybe this practical usage of `consume()` will help?
* [grammar](https://github.com/JanTvrdik/phpstan-type-parser/blob/65d08ecc823c06829e4689561ae9b30ae9506149/doc/grammer.peg)
* [parser](https://github.com/JanTvrdik/phpstan-type-parser/blob/65d08ecc823c06829e4689561ae9b30ae9506149/src/Parser.php) which uses consume

**Comment by dg** [comment]
I have no doubt it's practical, I use it too. https://github.com/nette/latte/blob/master/src/Latte/Compiler/TokenIterator.php#L161-L176
