### ISSUE TITLE
End of stream is not handled properly

### ISSUE THREAD

**Issue by jkuchar** [nette/tokenizer#19]
Version: 3.0.0

### Bug Description
```php
while ($token = $tokens->nextToken()) {
  // doSth()
}
```

should have consistent behaviour with
```php
$tokens->nextToken();
while ($token = $tokens->currentToken()) {
  $token->nextToken();
  // doSth()
}
```

When nextToken() reaches end of stream it does not increment internal position counter. Therefore second implementation ends up in infinite loop.

Please compare implementation from [Nette 2.1](https://github.com/nette/nette/blob/180d31fdae2b91ff6e98d7588d123f3d33f8c1de/Nette/Utils/TokenIterator.php#L195-L197) and [Nette 3.0](https://github.com/nette/tokenizer/blob/d462da8e951ba8ef820b9818972a7d0c49ac322d/src/Tokenizer/Stream.php#L219-L221) of `scan()` method

**Should I send PR which reverts to original behaviour?**

cc @Matej21

**Comment by jkuchar** [comment]
Any opinion on this? @dg

**Comment by dg** [comment]
So now I know what if does :-D  

I'll revert 35a55af9176926abc502a2e20dc533635e6d9884. And @jkuchar can you send test, please?

**Comment by jkuchar** [comment]
Merge request is ready #20. You can rebase/edit/squash/cherry-pick it. 🙂
